### ISSUE TITLE
dephpugger requirements => Uncaught Error: Call to undefined function Dephpug\Console\concerns\xdebug_is_enabled() in /home/hal/.config/composer/vendor/tacnoman/dephpugger/src/Dephpug/Console/concerns/PhpInfo.php:66

### ISSUE THREAD

**Issue by HalMorris** [tacnoman/dephpugger#51]
The full output is:
  ✔️ Your PHP version is 7.0 or more
  ✔️ XDebug is installed.
  ✔️ Sockets extension is installed.
PHP Fatal error:  Uncaught Error: Call to undefined function Dephpug\Console\concerns\xdebug_is_enabled() in /home/hal/.config/composer/vendor/tacnoman/dephpugger/src/Dephpug/Console/concerns/PhpInfo.php:66
Stack trace:
#0 /home/hal/.config/composer/vendor/tacnoman/dephpugger/src/Dephpug/Console/RequirementsCommand.php(36): Dephpug\Console\concerns\PhpInfo->xdebugIsActive()
#1 /home/hal/.config/composer/vendor/symfony/console/Command/Command.php(255): Dephpug\Console\RequirementsCommand->execute()
#2 /home/hal/.config/composer/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#3 /home/hal/.config/composer/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#4 /home/hal/.config/composer/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#5 /home/hal/.config/composer/vendor/tacnoman/dephpugger/src/Dephpug/Dephpugger.php(33): Symfony\Component\Console\Application->run()
#6 /home/hal/.config/composer in /home/hal/.config/composer/vendor/tacnoman/dephpugger/src/Dephpug/Console/concerns/PhpInfo.php on line 66

This is on ubuntu v20.10 with newly installed apache2, php 7.4.9, and /etc/php/7.4/mods-available/xdebug.ini:
zend_extension=/usr/lib/php/20190902/xdebug.so
xdebug.log="/opt/lampp/xdb-logs/xdebug.log"
xdebug.log_level=7
xdebug.client_host=127.0.0.1
xdebug.client_port=9005
xdebug.debug_mode=develop,debug,trace
xdebug.start_with_request=trigger
xdebug.collect_params=3

and 
/etc/php/7.4/apache2/conf.d/20-xdebug.ini	->	/etc/php/7.4/mods-available/xdebug.ini
/etc/php/7.4/cli/conf.d/20-xdebug.ini	->	/etc/php/7.4/mods-available/xdebug.ini

Thanks in advance for your help.

**Comment by HalMorris** [comment]
phpinfo
phpinfo()
PHP Version => 7.4.9

System => Linux praxis 5.8.0-38-generic #43-Ubuntu SMP Tue Jan 12 12:42:13 UTC 2021 x86_64
Build Date => Oct 26 2020 15:17:14
Server API => Command Line Interface
Virtual Directory Support => disabled
Configuration File (php.ini) Path => /etc/php/7.4/cli
Loaded Configuration File => /etc/php/7.4/cli/php.ini
Scan this dir for additional .ini files => /etc/php/7.4/cli/conf.d
Additional .ini files parsed => /etc/php/7.4/cli/conf.d/10-mysqlnd.ini,
/etc/php/7.4/cli/conf.d/10-opcache.ini,
/etc/php/7.4/cli/conf.d/10-pdo.ini,
/etc/php/7.4/cli/conf.d/15-xml.ini,
/etc/php/7.4/cli/conf.d/20-calendar.ini,
/etc/php/7.4/cli/conf.d/20-ctype.ini,
/etc/php/7.4/cli/conf.d/20-dom.ini,
/etc/php/7.4/cli/conf.d/20-exif.ini,
/etc/php/7.4/cli/conf.d/20-ffi.ini,
/etc/php/7.4/cli/conf.d/20-fileinfo.ini,
/etc/php/7.4/cli/conf.d/20-ftp.ini,
/etc/php/7.4/cli/conf.d/20-gettext.ini,
/etc/php/7.4/cli/conf.d/20-iconv.ini,
/etc/php/7.4/cli/conf.d/20-json.ini,
/etc/php/7.4/cli/conf.d/20-mbstring.ini,
/etc/php/7.4/cli/conf.d/20-mysqli.ini,
/etc/php/7.4/cli/conf.d/20-pdo_mysql.ini,
/etc/php/7.4/cli/conf.d/20-phar.ini,
/etc/php/7.4/cli/conf.d/20-posix.ini,
/etc/php/7.4/cli/conf.d/20-readline.ini,
/etc/php/7.4/cli/conf.d/20-shmop.ini,
/etc/php/7.4/cli/conf.d/20-simplexml.ini,
/etc/php/7.4/cli/conf.d/20-sockets.ini,
/etc/php/7.4/cli/conf.d/20-sysvmsg.ini,
/etc/php/7.4/cli/conf.d/20-sysvsem.ini,
/etc/php/7.4/cli/conf.d/20-sysvshm.ini,
/etc/php/7.4/cli/conf.d/20-tokenizer.ini,
/etc/php/7.4/cli/conf.d/20-xdebug.ini,
/etc/php/7.4/cli/conf.d/20-xmlreader.ini,
/etc/php/7.4/cli/conf.d/20-xmlwriter.ini,
/etc/php/7.4/cli/conf.d/20-xsl.ini

PHP API => 20190902
PHP Extension => 20190902
Zend Extension => 320190902
Zend Extension Build => API320190902,NTS
PHP Extension Build => API20190902,NTS
Debug Build => no
Thread Safety => disabled
Zend Signal Handling => enabled
Zend Memory Manager => enabled
Zend Multibyte Support => provided by mbstring
IPv6 Support => enabled
DTrace Support => available, disabled

Registered PHP Streams => https, ftps, compress.zlib, php, file, glob, data, http, ftp, phar
Registered Stream Socket Transports => tcp, udp, unix, udg, ssl, tls, tlsv1.0, tlsv1.1, tlsv1.2, tlsv1.3
Registered Stream Filters => zlib.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk, convert.iconv.*

This program makes use of the Zend Scripting Language Engine:
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.9, Copyright (c), by Zend Technologies
    with Xdebug v3.0.2, Copyright (c) 2002-2021, by Derick Rethans
